### ISSUE TITLE
sugestões/dicas/insights/correções visuais do site mkgcriacoes.com.br

### ISSUE THREAD

**Issue by ghost** [MarkusLuan/MeuPrimeiroJogo-jsWeb#13]
Oi pessoal.

Não sei onde abrir essa issue, então quero ajudar. Só peço gentileza e paciência já que sou novo por aqui. Tava pensando em ajudar a melhorar ainda mais o site mkgcriacoes.com.br.

*pensei em algo assim*
![image](https://user-images.githubusercontent.com/123137817/217660883-fdb964c9-e512-4e19-aee9-1b74db1a7d72.png)

como podemos ver tem ícone de dinheiro onde a pessoa clica e poderia ser redirecionada ao paypal ou algo assim. 

tomara que esteja ajudando do que atrapalhando. se isso for relevante, fico feliz em ajudar.

*algo que percebi é que o site mkgcriacoes não é responsivo, e isso pode dificultar quem acessa pelo celular do que pelo desktop, se a intenção for facilitar o acesso para quem utiliza mobile, acho que vale apena a responsividade do site, em caso contrário não*

**Comment by MarkusLuan** [comment]
@mindcrazy , muito obrigado mano pela ajuda.
Muito boa essa dica. Realmente falhei na responsividade de algumas partes do site, mas em breve vou ajeitar.

E infelizmente, não posso deixar o repositório como público, por questões de segurança. Mas pode abrir as issues por aqui mesmo.
