### ISSUE TITLE
website para MeuPrimeiroJogo-jsWeb

### ISSUE THREAD

**Issue by ghost** [MarkusLuan/MeuPrimeiroJogo-jsWeb#4]
Oi MarkusLuan.

Uma ideia interessante que tive hoje após ter um feedback que recebi de você - seria sobre adicionar uma página do GitHub pages, assim as pessoas jogam online sem precisar de baixar o código fonte para isso.

*O que você pensa dessa ideia?*

**Comment by MarkusLuan** [comment]
Opa mano, bom dia.
Estava pensando em colocar no meu site, aí colocaria apenas o link no readme.md

**Comment by MarkusLuan** [comment]
Não sei. Qual seria a vantagem em si?
Que no site meio que fica mais centralizado meus projetos em execução e atraíra para os outros apps e jogos também, sei lá.

**Comment by MarkusLuan** [comment]
Acho que entendi.
A vantagem mesmo seria a questão da url mais personalizável, já que no site eu pago anual por um domínio (mkgcriacoes.com.br), e tenho acesso ilimitado a subdomínios.

Só que em relação ao resto, o site e servidor são totalmente personalizáveis e integrado com o github. Se faço um push para o master de algum projeto que esteja no site, automaticamente já faz o deploy.

Aí não sei se faria tanto sentido entende?
Mas quanto a organização já tenho - @MkgCriacoes

**Comment by MarkusLuan** [comment]
show de bola. Feito.
